# lab_capacity_seeds
Lab.find_by(name: '相澤 山崎研').update(capacity: 4)
Lab.find_by(name: '苗村研').update(capacity: 2)
Lab.find_by(name: '鶴岡研').update(capacity: 2)
Lab.find_by(name: '伊庭 長谷川研').update(capacity: 4)
Lab.find_by(name: '峯松 斎藤研').update(capacity: 4)
Lab.find_by(name: '川原研').update(capacity: 2)
Lab.find_by(name: '相田 矢谷研').update(capacity: 4)
Lab.find_by(name: '江崎 落合研').update(capacity: 4)
Lab.find_by(name: '森川研').update(capacity: 2)
Lab.find_by(name: '坂井 入江研').update(capacity: 4)
Lab.find_by(name: '田浦研').update(capacity: 2)
Lab.find_by(name: '浅田 名倉 飯塚研').update(capacity: 3)
Lab.find_by(name: '藤田研').update(capacity: 1)
Lab.find_by(name: '松橋研').update(capacity: 1)
Lab.find_by(name: '池田研').update(capacity: 1)
Lab.find_by(name: '三田研').update(capacity: 1)
Lab.find_by(name: '廣瀬研').update(capacity: 1)
Lab.find_by(name: '山下研').update(capacity: 1)
Lab.find_by(name: '小関研').update(capacity: 1)
Lab.find_by(name: '中野 種村研').update(capacity: 2)
Lab.find_by(name: '八井研').update(capacity: 1)
Lab.find_by(name: '高木 竹中研').update(capacity: 2)
Lab.find_by(name: '田畑研').update(capacity: 1)
Lab.find_by(name: '田中 大矢研').update(capacity: 2)
Lab.find_by(name: '染谷 横田研').update(capacity: 2)
Lab.find_by(name: '杉山研').update(capacity: 1)
Lab.find_by(name: '日高 熊田研').update(capacity: 2)
Lab.find_by(name: '小野靖研').update(capacity: 1)
Lab.find_by(name: '小野亮研').update(capacity: 1)
Lab.find_by(name: '堀 藤本研').update(capacity: 2)
Lab.find_by(name: '横山研').update(capacity: 1)
Lab.find_by(name: '大崎研').update(capacity: 1)
Lab.find_by(name: '古関研').update(capacity: 1)
Lab.find_by(name: '馬場研').update(capacity: 1)
Lab.find_by(name: '関野研').update(capacity: 1)
