Lab.create(name: '相澤 山崎研')
Lab.create(name: '苗村研')
Lab.create(name: '鶴岡研')
Lab.create(name: '伊庭 長谷川研')
Lab.create(name: '峯松 斎藤研')
Lab.create(name: '川原研')
Lab.create(name: '相田 矢谷研')
Lab.create(name: '江崎 落合研')
Lab.create(name: '森川研')
Lab.create(name: '坂井 入江研')
Lab.create(name: '田浦研')
Lab.create(name: '浅田 名倉 飯塚研')
Lab.create(name: '藤田研')
Lab.create(name: '松橋研')
Lab.create(name: '池田研')
Lab.create(name: '三田研')
Lab.create(name: '廣瀬研')
Lab.create(name: '山下研')
Lab.create(name: '小関研')
Lab.create(name: '中野 種村研')
Lab.create(name: '八井研')
Lab.create(name: '高木 竹中研')
Lab.create(name: '田畑研')
Lab.create(name: '田中 大矢研')
Lab.create(name: '染谷 横田研')
Lab.create(name: '杉山研')
Lab.create(name: '日高 熊田研')
Lab.create(name: '小野靖研')
Lab.create(name: '小野亮研')
Lab.create(name: '堀 藤本研')
Lab.create(name: '横山研')
Lab.create(name: '大崎研')
Lab.create(name: '古関研')
Lab.create(name: '馬場')
Lab.create(name: '関野')
