# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

## Subjects
### 2A
Subject.create(key: "数学1D", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "生命科学概論", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "数理手法Ⅰ", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "数理手法Ⅴ", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "ディジタル回路", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "電子基礎物理", weight: "4", semester: 4, subject_type: "all")
Subject.create(key: "エネルギー工学", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "電気電子数学演習", weight: "3", semester: 4, subject_type: "all")
Subject.create(key: "電気電子計測", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "電子デバイス基礎", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "電気磁気学Ⅰ", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "電気磁気学Ⅱ", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "電気回路理論第一", weight: "4", semester: 4, subject_type: "all")
Subject.create(key: "ソフトウェアⅠ", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "ソフトウェアⅡ", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "情報通信理論", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "信号解析基礎", weight: "2", semester: 4, subject_type: "all")
Subject.create(key: "プログラミング基礎演習", weight: "1.5", semester: 4, subject_type: "all")

### 3S
Subject.create(key: "制御工学第一", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "アルゴリズム", weight: "2", semester: 5, subject_type: "denjo")
Subject.create(key: "電気機器学基礎", weight: "2", semester: 5, subject_type: "denden")
Subject.create(key: "コンピュータアーキテクチャ", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "信号処理工学", weight: "2", semester: 5, subject_type: "denjo")
Subject.create(key: "電子物性基礎", weight: "2", semester: 5, subject_type: "denden")
Subject.create(key: "半導体デバイス工学", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "数学2D", weight: "4", semester: 5, subject_type: "denden")
Subject.create(key: "数学2G", weight: "2", semester: 5, subject_type: "denjo")
Subject.create(key: "統計的機械学習", weight: "2", semester: 5, subject_type: "denjo")
Subject.create(key: "電磁波工学", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "特許法", weight: "1", semester: 5, subject_type: "all")
Subject.create(key: "ネットワーク工学概論", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "電気回路理論第二", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "電気電子情報工学倫理", weight: "1", semester: 5, subject_type: "all")
Subject.create(key: "電子回路Ⅰ", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "ハードウェア設計論", weight: "2", semester: 5, subject_type: "all")
Subject.create(key: "電気電子情報実験・演習第一", weight: "6", semester: 5, subject_type: "all")

### 3S other
Subject.create(key: "アントレプレナーシップⅠ", weight: "1", semester: 5, subject_type: "other")
Subject.create(key: "アントレプレナーシップⅡ", weight: "1", semester: 5, subject_type: "other")
Subject.create(key: "先端技術と社会特別講義Ⅰ", weight: "2", semester: 5, subject_type: "other")
Subject.create(key: "創造的プロジェクトⅠ", weight: "1.5", semester: 5, subject_type: "other")
Subject.create(key: "創造的プロジェクトⅢ", weight: "1.5", semester: 5, subject_type: "other")
Subject.create(key: "スパコンプログラミング", weight: "2", semester: 5, subject_type: "other")
Subject.create(key: "メディコンⅠ", weight: "1", semester: 5, subject_type: "other")
Subject.create(key: "VLSIアーキテクチャ", weight: "2", semester: 5, subject_type: "other")
Subject.create(key: "VLSI設計工学", weight: "2", semester: 5, subject_type: "other")



## Labs
Lab.create(name: '相澤 山崎研', capacity: 4)
Lab.create(name: '苗村研', capacity: 2)
Lab.create(name: '鶴岡研', capacity: 2)
Lab.create(name: '伊庭 長谷川研', capacity: 4)
Lab.create(name: '峯松 斎藤研', capacity: 4)
Lab.create(name: '川原研', capacity: 2)
Lab.create(name: '相田 矢谷研', capacity: 4)
Lab.create(name: '江崎 落合研', capacity: 4)
Lab.create(name: '森川研', capacity: 2)
Lab.create(name: '坂井 入江研', capacity: 4)
Lab.create(name: '田浦研', capacity: 2)
Lab.create(name: '浅田 名倉 飯塚研', capacity: 3)
Lab.create(name: '藤田研', capacity: 1)
Lab.create(name: '松橋研', capacity: 1)
Lab.create(name: '池田研', capacity: 1)
Lab.create(name: '三田研', capacity: 1)
Lab.create(name: '廣瀬研', capacity: 1)
Lab.create(name: '山下研', capacity: 1)
Lab.create(name: '小関研', capacity: 1)
Lab.create(name: '中野 種村研', capacity: 2)
Lab.create(name: '八井研', capacity: 1)
Lab.create(name: '高木 竹中研', capacity: 2)
Lab.create(name: '田畑研', capacity: 1)
Lab.create(name: '田中 大矢研', capacity: 2)
Lab.create(name: '染谷 横田研', capacity: 2)
Lab.create(name: '杉山研', capacity: 1)
Lab.create(name: '日高 熊田研', capacity: 2)
Lab.create(name: '小野靖研', capacity: 1)
Lab.create(name: '小野亮研', capacity: 1)
Lab.create(name: '堀 藤本研', capacity: 2)
Lab.create(name: '横山研', capacity: 1)
Lab.create(name: '大崎研', capacity: 1)
Lab.create(name: '古関研', capacity: 1)
Lab.create(name: '馬場研', capacity: 1)
Lab.create(name: '関野研', capacity: 1)
Lab.create(name: 'デジタルハリウッド大', capacity: 1)