# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

### 3A other
Subject.create(key: "計算論", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "制御工学第二", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "映像メディア工学", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "VLSI工学基礎", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "エネルギー変換工学", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "電気電子情報実験・演習第二", weight: "6", semester: 6, subject_type: "all")
Subject.create(key: "オペレーティングシステム", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "電磁界応用工学", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "人工知能", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "光電子工学Ⅰ", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "電力システム工学第一", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "電気系特別講義第二", weight: "1", semester: 6, subject_type: "other")
Subject.create(key: "数学3", weight: "2", semester: 6, subject_type: "other")
Subject.create(key: "ヒューマンインターフェース工学", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "電子量子力学Ⅰ", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "システム数理工学", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "数理手法Ⅲ", weight: "2", semester: 6, subject_type: "other")
Subject.create(key: "脳科学入門", weight: "2", semester: 6, subject_type: "other")
Subject.create(key: "職業指導", weight: "2", semester: 6, subject_type: "other")
Subject.create(key: "国際経済学", weight: "2", semester: 6, subject_type: "other")
Subject.create(key: "情報通信工学", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "電離気体論", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "分散システム", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "光電子デバイス", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "パワーエレクトロニクス", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "メディアコンテンツ特別講義Ⅱ", weight: "1", semester: 6, subject_type: "other")
Subject.create(key: "言語・音声情報処理", weight: "2", semester: 6, subject_type: "denjo")
Subject.create(key: "電子回路Ⅱ", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "電子情報機器学", weight: "2", semester: 6, subject_type: "all")
Subject.create(key: "電子物性第一", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "電気機器CAD演習", weight: "2", semester: 6, subject_type: "denden")
Subject.create(key: "無線通信応用工学", weight: "2", semester: 6, subject_type: "denjo")